spring:
  application:
    name: auth-server
  profiles:
    default: default
  config:
    import: "optional:configserver:http://localhost:7777/"
  datasource:
    url: jdbc:h2:mem:usersdb
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update


h2:
  console:
    enabled: true

server:
  port: 3030
  servlet:
    context-path: /auth-server

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
