server:
  port: 0
spring:
  application:
    name: report-listener
  profiles:
    default: default
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      function:
        bindings: #Consumer-out -> consumerReport <- Consumer-in
          consumerReport-in-0:
            destination: consumerReport
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      username: root
      password: root
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/