server:
  port: 0
spring:
  application:
    name: report-listener
  profiles:
    default: default
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_SERVER}
      function:
        bindings: #Consumer-out -> consumerReport <- Consumer-in
          consumerReport-in-0:
            destination: consumerReport
  data:
    mongodb:
      authentication-database: ${MONGO_AUTH_DB}
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      username: ${MONGO_USER}
      password: ${MONGO_PASS}
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER}