spring:
  application:
    name: gateway
  profiles:
    default: default
server:
  port: 4040
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER}