logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  port: 0
  servlet:
    context-path: /companies-crud

spring:
  application:
    name: companies-crud
  kafka:
    listener:
      ack-mode: manual_immediate
    consumer:
      bootstrap-servers: ${KAFKA_SERVER}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: circuitbreaker
  profiles:
    default: default
  config:
    import: "optional:configserver:${CONFIG_SERVER}"
  datasource:
    hikari:
      connection-timeout: ${db.connection-timeout}
      maximum-pool-size: ${db.maximum-pool-size}
    password: ${db.password}
    url: ${db.url}
    username: ${db.username}

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER}