spring:
  application:
    name: reports-fallback
server:
  port: 8787
  servlet:
    context-path: /reports-fallback
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
