server:
  port: 0
  servlet:
    context-path: /report-ms
spring:
  application:
    name: report-ms
  profiles:
    default: default
  config:
    import: "optional:configserver:${CONFIG_SERVER}"
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_SERVER}
      function:
        bindings:
          consumerReport-out-0:
            destination: consumerReport
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER}
